modified bookmark script

diff --git a/binaries/bookmark b/binaries/bookmark
--- a/binaries/bookmark
+++ b/binaries/bookmark
@@ -1,26 +1,41 @@
-#!/bin/bash
+#!/bin/sh
 STRGDIR="$HOME/.local/share/bookmarks"
 if ! [ -f "$STRGDIR" ]; then 
 	mkdir --parent "$STRGDIR" || exit
 fi
 
+command -v dmenu >/dev/null 2>&1 || { echo >&2 "dmenu is required."; }
+command -v xclip >/dev/null 2>&1 || { echo >&2 "xclip is required."; }
+command -v dunst >/dev/null 2>&1 || { echo >&2 "dunst is required."; }
+command -v dunstify >/dev/null 2>&1 || { echo >&2 "dunstify is required."; }
 
-#IF bookmark -s then we are storing and should use this format
-if [ "$1" = "-s" ]; then
-	#Bookmark whatever you had selected.
-	#List of files that we use to store the things
-	LOCS=$(ls "$STRGDIR")
-	SELECTION=$(echo "$LOCS" | dmenu -l 5 -p "Select or Create File to Save to:")
-	
-	#Give me the contnt from primary register
-	CONTENT=$(xclip -o)
-	BKMRKS=$(awk -F: '{print $1}' "$STRGDIR/$SELECTION")
-	NAME=$(echo "$BKMRKS" | dmenu -l 5 -p "Name of Bookmark:")
+if [ -z "$1" ] || [ "$1" = "-s" ]; then
+  # Bookmarking
+  CHOICE=$( ls "$STRGDIR" | demnu -l 5 -p "Select or Create File to save to:" )
+
+  if [ "$CHOICE" = 0 ]; then
+				dunstify -a Bookmark "Bookmark canceled."
+				exit 0
+  fi
+
+  # Get highlighted text (Primary register)
+  CNTNT=$(xclip -selection "primary")
+
+  # Existing bookmarks
+  BKMKS=$(awk -F: '{print $1}' "$STRGDIR/$CHOICE")
+
+  # User-Selected name of bookmark
+  NAME=$(echo "$BKMKS" | dmenu -l 5 -p "Name of bookmark:")
+
+  if [ "$NAME" = 0 ]; then
+				dunstify -a Bookmark "Bookmark canceled."
+				exit 0
+  fi
 
 	#Create the file if it doenst exist
-	if ! [ -f "$STRGDIR/$SELECTION" ]; then
-		touch "$STRGDIR/$SELECTION"
-		echo "$NAME:$CONTENT" >> "$STRGDIR/$SELECTION"
+	if ! [ -f "$STRGDIR/$CHOICE" ]; then
+		touch "$STRGDIR/$CHOICE"
+		echo "$NAME:$CNTNT" >> "$STRGDIR/$CHOICE"
 	else 
 	# Check to see if the name specified is a bookmark
 		case $NAME in 
@@ -30,20 +45,20 @@ if [ "$1" = "-s" ]; then
 			awk '/'"$NAME"'\:/ {print}' | xclip -selection clipboard
 
 			# IF Y selected then overwrite it w/ sed
-			if ! [ "$NAMECNT" == "y" ] && ! [ "$NAMECNT" == "Y" ]; then
+			if ! [ "$NAMECNT" = "y" ] && ! [ "$NAMECNT" = "Y" ]; then
 				dunstify -a Bookmark "Bookmark canceled."
 				exit 0
 			fi
 
 			#Replace old entry
-			sed -i 's/&'"$NAME"'\:.*/'"$CONTENT"'/' "$STRGDIR/$SELECTION"
+			sed -i 's/&'"$NAME"'\:.*/'"$CNTNT"'/' "$STRGDIR/$CHOICE"
 				;;
 			*)
-			echo "$NAME:$CONTENT" >> "$STRGDIR/$SELECTION"
+			echo "$NAME:$CNTNT" >> "$STRGDIR/$CHOICE"
 				;;
 		esac
 	fi
-	
+
 	dunstify -a Bookmark "Bookmark $NAME Saved to $STRGDIR/$SELECTION"
 
 #If bookmark -r then we are retrieving from the file
